[package]
name = "generate-littlewood"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
poly = {path = "../lib"}
serde_json = "1.0.114"
heck = { version = "0.5.0-rc.1" }
polynomen = "1.1.0"

[lib]
path = "./src/generate.rs"
